config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  devise_for :users

  resources :secure_files, only: [:index, :new, :create, :destroy]
  root "secure_files#index"


  #fetch from tiny url
   get '/s/:slug', to: 'tiny_urls#show', as: :short
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/secure_file.rb
class SecureFile < ApplicationRecord

  has_secure_token :guid

  # uploader config
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  # validations
  validates :name, :attachment, presence: true # Make sure the owner's name is present.

  #callbacks
  before_create :generate_tyny_url
  after_commit :remove_attachment!, on: :destroy

  # associations
  belongs_to :user

  private

  def generate_tyny_url
    self.tiny_url = TinyUrl.shorten(file_url)
  end

  def file_url
    return "/uploads/secure_file/attachment/#{self.guid}/#{self.attachment.filename}"
  end
end

app/models/tiny_url.rb
class TinyUrl < ApplicationRecord


  #validations
  validates_presence_of :url
  # validates :url, format: URI::regexp(%w[http https])
  validates_uniqueness_of :slug
  validates_length_of :url, within: 3..255, on: :create, message: "too long"
  validates_length_of :slug, within: 3..255, on: :create, message: "too long"

  # auto slug generation
  before_validation :generate_slug

  def generate_slug
    self.slug = SecureRandom.uuid[0..5] if self.slug.nil? || self.slug.empty?
    true
  end

  # fast access to the shortened link
  def short
    Rails.application.routes.url_helpers.short_url(slug: self.slug)
  end

  # the Generator
  def self.shorten(url, slug = '')
    link = TinyUrl.where(url: url, slug: slug).first
    return link.short if link

    link = TinyUrl.new(url: url, slug: slug)
    return link.short if link.save

    TinyUrl.shorten(url, slug + SecureRandom.uuid[0..2])
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #associations
  has_many :secure_files

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/secure_files_controller.rb
class SecureFilesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_authorization, only: [:create, :new]

  def index
    @secure_files = current_user.secure_files.all
  end

  def new
    @secure_file = current_user.secure_files.new
  end

  def create
    @secure_file = current_user.secure_files.new(secure_file_params)

    if @secure_file.save
      redirect_to secure_files_path, notice: "Successfully uploaded."
    else
      render "new"
    end

  end

  def destroy
    @secure_file = current_user.secure_files.find(params[:id])
    @secure_file.destroy
    redirect_to secure_files_path, notice:  "Successfully deleted."
  end

  private
  def secure_file_params
    params.require(:secure_file).permit(:name, :attachment)
  end

  def check_authorization
    redirect_to secure_files_path, notice: "Not allowed to perform this action, kindly ask admin to verify your account." unless current_user.is_verified?
  end

end

app/controllers/tiny_urls_controller.rb
class TinyUrlsController < ApplicationController

  def show
    @link = TinyUrl.find_by_slug(params[:slug])

    render file: "/public/404.html", layout: false, status: 404 if @link.nil?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secure_files_helper.rb
module SecureFilesHelper
end

app/helpers/tiny_urls_helper.rb
module TinyUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecureUpload</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
    <%= yield %>
  </body>
</html>

app/views/secure_files/create.html.erb
<h1>SecureFiles#create</h1>
<p>Find me in app/views/secure_files/create.html.erb</p>

app/views/secure_files/destroy.html.erb
<h1>SecureFiles#destroy</h1>
<p>Find me in app/views/secure_files/destroy.html.erb</p>

app/views/secure_files/index.html.erb
<div class="container">
  <br>

  <%= link_to "Upload new file", new_secure_file_path %>
  <br>
  <br>

  <table border="3">
    <thead>
    <tr>
      <th>File Name</th>
      <th>Download Link</th>
      <th>Action</th>
      <th>Public Url</th>
    </tr>
    </thead>

    <tbody>
    <% @secure_files.each do |secure_file| %>

      <tr>
        <td><%= secure_file.name %></td>
        <td><%= link_to "Download", secure_file.attachment_url %></td>
        <td><%= link_to "Delete",  secure_file, method: :delete, confirm: "Are you sure you want to delete #{secure_file.name}?" %></td>
        <td><%= secure_file.tiny_url %></td>
      </tr>

    <% end %>
    </tbody>

  </table>
</div>

app/views/secure_files/new.html.erb
<div class="container">
  <div>
    <% @secure_file.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    <div class="container">
      <div>
        <%= form_for @secure_file, html: { multipart: true } do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>
          <br><br>
          <%= f.label :attachment %>
          <%= f.file_field :attachment %>
          <br>
          <%= f.submit "Save" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tiny_urls/show.html.erb
<% if user_signed_in? %>
  <%= link_to "Goto Homepage", root_path %>
<% end %>

<p>Here is your download link, kindly do not share it with anyone.</p>
<td><%= link_to "Download", @link.url %></td>